task default: %w[test]

task :test do
  sh "skeptic --lines-per-method 10 --line-length 80 --max-nesting-depth 2 --no-semicolons --no-trailing-whitespace --check-syntax --no-global-variables --english-words-for-names='bgn usd eur gbp leva dollars euro pounds' --naming-conventions solution.rb"

  puts "\n"

  sh 'rspec spec.rb --require ./solution.rb --colour --format documentation'
end
